### ISSUE TITLE
Does not build with node v4.x

### ISSUE THREAD

**Issue by weagle08** [gammasoft/pemutils#1]
this project does not build on Windows for node v4.x.

**Comment by weagle08** [comment]
turns out you just have to update the version of x509 you are dependent upon for building with node v4.x.

**Comment by renatoargh** [comment]
Hey @weagle08 sorry for taking this long. I thought that semver would take care of this but I just realized that `^` might not get the right version of x509 for node v4. 

What x509 version is working properly with node v4? Thanks.
