### ISSUE TITLE
No public key returned

### ISSUE THREAD

**Issue by weagle08** [gammasoft/pemutils#2]
Is there a reason you are removing the public key from the attributes when you return the certificate object?

**Comment by renatoargh** [comment]
I will be totally honest with you; I just can't remember why.

**Comment by renatoargh** [comment]
This was just by mistake. Its up to the user to decide if he want or not this property on his own code. [Will remove line 75 in the upcoming version](https://github.com/gammasoft/pemutils/blob/7d3a082807b8850ce021f8570b627a7c0d7302e6/index.js#L75). 

If you need something to be added please send pull requests or let me know what would be useful to you before I publish new version to npm. Thanks.
